version: "3.3"
services:
  bitcoind-regtest:
    container_name: bitcoind-regtest
    build:
      context: ../bitcoind-regtest/.
      dockerfile: ./Dockerfile
    image: lnbook/bitcoind_regtest:latest
    ports:
    - "12001:12001"
  lnd-run:
    container_name: lnd-run
    build:
      context: ../lnd-run
      dockerfile: ./Dockerfile
    image: lnbook/lnd_run:latest
